spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://slang-database.chyq0kgmmn8p.ap-northeast-2.rds.amazonaws.com:3306/slang
    username: yh0872
    password: rj7783208232
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 7e5b8ef6a9c2444a87f5db5dd3f9d9e3d8f8b5a1d6c2b4d4e1e2f3a4b5c6d7e8
