spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(erq55A/W3XQeZI/1F7DVhFrMZqbgigKwQzKvUIHDQxx2YymDxXztsSazDbExnMR1gx+dEy8sOjUSw/ap5e6xXI0tsukSnQ/+Kukb7r/fWBUzOtNvMC6dP0KAZYqklWVu)
    username: ENC(ak7Kf4/WWJAfYjVAdbcJog==)
    password: ENC(ftqvyn0/xCvAndLEZ6huOZIX+ArNM+d+)
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ENC(K2IDhap15eAbkYnCFLWoIpD0yWHXoGVjBs1eIg4QrFIMjSViP9yDQIq+W78E0qNCFZv+uzgXDY5KnkiYhoR4FOMv85Zzl0a1tFUIQBatS3s=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

gpt:
  model: gpt-3.5-turbo
  api:
    key: ENC(R8ZQSOInq81I1YpP+sVaxYG5qEIKWi+Ur00FJ0c4ucWHSPbr1E2KddDkf2QCyD3kui2BQJfaic5iUsRluehToFIWShDNh8Ho)
    url: https://api.openai.com/v1/chat/completions
